global:
  domain: vucongtuanduong.dpdns.org
  prefix: web-dev1

image:
  registry: docker.io
  repository: vucongtuanduong/web-grading-system-api-gateway
  tag: "v1.0.3"
  pullPolicy: Always

spring:
  profilesActive: stg
  dbName: api_gateway_db

observability:
  region: dev
  cluster: k3s-local

serviceUris:
  assignment: http://grading-assignment-service:8081
  submission: http://grading-submission-service:8082
  result: http://grading-result-service:8084

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
