global:
  domain: vucongtuanduong.dpdns.org
  prefix: web-dev1

image:
  registry: docker.io
  repository: vucongtuanduong/web-grading-system-result-service
  tag: "v1.0.3"
  pullPolicy: Always

spring:
  profilesActive: stg
  dbName: result_db

observability:
  region: dev
  cluster: k3s-local

service:
  type: ClusterIP
  port: 8084

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
