apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "executor-service.fullname" . }}
  labels:
    app: {{ include "executor-service.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "executor-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "executor-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profilesActive }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PORT
            - name: DB_NAME
              value: {{ .Values.spring.dbName }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: REGION
              value: {{ .Values.observability.region | quote }}
            - name: CLUSTER
              value: {{ .Values.observability.cluster | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
